services:
  katana:
    build:
      context: .
      dockerfile: ./deployment/katana.Dockerfile
    container_name: dojo-katana
    ports:
      - "5050:5050"
    restart: unless-stopped
    networks:
      - dojo

  torii:
    build:
      context: .
      dockerfile: ./deployment/torii.Dockerfile
    container_name: dojo-torii
    restart: unless-stopped
    environment:
      - WORLD_ADDRESS=0x79a3c37167370f03882049edbb291a4c8b79b988835184a18a0695f4dc4fe0c
      - RPC_URL=http://katana:5050
    ports:
      - "8080:8080"
    depends_on:
      katana:
        condition: service_started
    networks:
      - dojo

  web:
    build:
      context: .
      dockerfile: ./deployment/web.Dockerfile
    container_name: dojo-web
    restart: unless-stopped
    environment:
      - PORT=5173
    ports:
      - "5173:5173"
    depends_on:
      torii:
        condition: service_started
    networks:
      - dojo

networks:
  dojo:
    driver: bridge