# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }} 
#   namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
# spec:
#   podSelector:
#     matchLabels:
#       app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }} 
#   policyTypes:
#   - Ingress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           name: traefik