/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      const name = "Game";
      return defineComponent(
        world,
        {
          game_id: RecsType.Number,
          state: RecsType.Number,
          player1: RecsType.Number,
          player2: RecsType.Number,
          player1_hash: RecsType.Number,
          player2_hash: RecsType.Number,
          player1_commit: RecsType.Number,
          player2_commit: RecsType.Number,
          started_timestamp: RecsType.Number,
          winner: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          wins: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
